#pragma once

#define DEBUG
//#define PRINT_RECV_PACKET
#define PRINT_SEND_PACKET

//#define DISABLE_XIGNCODE

#define DEVELOPER_ONLY
#define SPECIAL_FEATURES
#define ENABLE_CAPTCHA_SOLVER

#define DISABLE_USKO_AUTO_SERVER_SELECT
//#define NO_INITIALIZE_CLIENT_HANDLER
//#define DISABLE_AUTO_LOGIN

//#define ENABLE_FIREWALL_RULES

#define SET_DEBUG_CLIENT_INFORMATION

#define DEVELOPMENT_PATH "C:\\NTTGame\\KnightOnlineEn"
#define DEVELOPMENT_EXE "KnightOnLine.exe"
#define DEVELOPMENT_PLATFORM 0
#define DEVELOPMENT_ACCOUNT_INDEX 5

//#define DEVELOPMENT_PATH "C:\\CNKO"
//#define DEVELOPMENT_EXE "KnightOnLine.exe"
//#define DEVELOPMENT_PLATFORM 1
//#define DEVELOPMENT_ACCOUNT_INDEX 0

//#define DEVELOPMENT_PATH "C:\\Ongate\\KnightOnline"
//#define DEVELOPMENT_EXE "knightonline.exe"
//#define DEVELOPMENT_PLATFORM 3
//#define DEVELOPMENT_ACCOUNT_INDEX 1

#define MAX_ATTACK_RANGE		50.0f
#define MAX_VIEW_RANGE		100.0f