#pragma once

//#define DEBUG
//#define PRINT_RECV_PACKET
//#define PRINT_SEND_PACKET

//#define DISABLE_XIGNCODE

//#define NO_INITIALIZE_CLIENT_HANDLER

#define DEBUG_AUTO_LOGIN
#define DEVELOPMENT_PATH "C:\\NTTGame\\KnightOnlineEn"
#define DEVELOPMENT_EXE "KnightOnLine.exe"
#define DEVELOPMENT_PLATFORM 0
#define DEVELOPMENT_ACCOUNT_INDEX 1

//#define DEVELOPMENT_PATH "C:\\CNKO"
//#define DEVELOPMENT_EXE "KnightOnLine.exe"
//#define DEVELOPMENT_PLATFORM 1
//#define DEVELOPMENT_ACCOUNT_INDEX 0

#define MAX_ATTACK_RANGE		50.0f
#define MAX_VIEW_RANGE		100.0f